services:
  - type: web
    name: donation-management-api
    runtime: docker  # Changed from python to docker
    repo: https://github.com/chandrashekharddev/DonationManagement-Backend
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
